http:
  address: 0.0.0.0
  port: 8080

grpc:
  account_service:
    address: 127.0.0.1
    port: 11001

cache:
  type: redis
  address: 127.0.0.1
  port: 6379
  username: ""
  password: ""

auth:
  token:
    secret: "secret_token_in_here"
    accessTokenTTL: 15m
    refreshTokenTTL: 24h
    refreshTokenLongTTL: 720h

log:
  level: debug
